### PR TITLE
New branch for spark 1.5.1

### PR DESCRIPTION
**Pull request by zhichao-li**

### CODE REVIEW

**Comment by zhichao-li** [comment]
@chenghao-intel @adrian-wang could you take a look at this?

**Comment by adrian-wang** [comment]
why change some file from 755 -> 644?

**Comment by adrian-wang** [comment]
Also, pls submit a separate pr for pom and travis

**Comment by chenghao-intel** [comment]
Still, I think the most struggling thing is about the SQLParser, as I don't want to maintain the code in StreamingSQL, we definitely need to think about the workaround solution.

In the meantime, as @adrian-wang suggested, can you split this PR into couple of separated ones?

@adrian-wang can you update the travis file for all of the branch?

**Comment by zhichao-li** [comment]
@chenghao-intel I haven't find a good solution for integrate the `SQLParser` since we need lots of dependencies on that if want to support the window operation. let's discuss this offline.

**Comment by adrian-wang** [comment]
Maybe we can use hive parser and `HiveQl`?

**Comment by chenghao-intel** [comment]
As we are targeting the Spark 1.5.x and probably 1.6.x, Using HiveQl maybe requires more code change.

**Comment by zhichao-li** [comment]
check fail again , not sure if we need to increase the log limitation:
 "The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over)."
Log of the unittest alone is around 1.4M

**Comment by zhichao-li** [comment]
retest this please.

**Comment by adrian-wang** [comment]
- window function *** FAILED ***
  ListBuffer("[1,2]", "[2,2]", "[3,2]", "[1,4]", "[2,4]", "[3,4]", "[1,6]", "[2,6]", "[3,6]", "[1,6]", "[2,6]", "[3,6]") did not equal List("[1,2]", "[2,2]", "[3,2]", "[1,4]", "[2,4]", "[3,4]", "[1,6]", "[2,6]", "[3,6]", "[1,6]", "[2,6]", "[3,6]", "[1,6]", "[2,6]", "[3,6]") (BasicFunctionTestSuite.scala:112)

**Comment by zhichao-li** [comment]
en, need to take a look at the window test. but the good thing is the problem of log length has been addressed.

**Comment by chenghao-intel** [comment]
any more work that we need to do before merging it?

**Comment by chenghao-intel** [comment]
Still, I suggest to submit separated PR for different purpose. At least:
1) Travis log
2) CheckStyle
3) 1.5.1 Support

**Comment by zhichao-li** [comment]
@chenghao-intel  I'll separate those shortly.

**Comment by zhichao-li** [comment]
Just have a second thought, actually "Travis log" should be together with "1.5.1 Support" otherwise "1.5.1 Support" would not pass the travis build. or I can remove #1, #2 from the current patch first, and merge the clean version(no matter it pass the travis or not), then add #1， #2 back in separated prs.

**Comment by chenghao-intel** [comment]
I don't think `conf/travis_log4j.properties` have to goes into the code along with this PR, can you create a separate PR for this?

**Pull request merged**
