### PR TITLE
Support spark 1.5.1

### PR DESCRIPTION
**Pull request by zhichao-li**

### CODE REVIEW

**Comment by chenghao-intel** [comment]
can you try to merge into another branch, instead of master?

**Comment by adrian-wang** [comment]
@chenghao-intel we can review here, and directly push to a new branch

**Comment by chenghao-intel** [comment]
And another 2 issues in high level:
1. Split the PR into 2 (one for removing the sbt, and another for the migration of Spark 1.5.1)
2. I am wondering if we have some trick way to avoid copying the SqlParser code directly.

**Comment by happycherry** [comment]
Build finished. No test results found.

**Comment by zhichao-li** [comment]
https://github.com/Intel-bigdata/spark-streamingsql/pull/22 has been created to replace this one.

**Pull request closed without merging**
